spring:
  application:
    name: countries-service
  jpa:
    show-sql: true
  h2:
    console:
       enabled: true
server:
  port: 0
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
    